Pin down NEURON on macOS
NEURON 9.0 and up compiles `.mod` files to C++ instead of C.
This is incompatible with our `.mod` files, as they have VERBATIM
blocks, which are valid C code, but not always valid C++ code.

For example, `ProbAMPANMDA2.mod` has the VERBATIM block:
```c
#include<stdlib.h>
#include<stdio.h>
#include<math.h>

double nrn_random_pick(void* r);
void* nrn_random_arg(int argpos);
```

This however overloads a previous definition from:
```c
.pixi/envs/default/lib/python3.9/site-packages/neuron/.data/include/nrnrandom.h:6:7:
note: previous declaration is here
    6 | Rand* nrn_random_arg(int);
      | ~~~~~ ^
```

Overloading functions with a different return type is OK in C, but not
in C++:
```cpp
error: functions that differ only in their return type cannot be
overloaded
```

Rather than making our VERBATIM blocks C++-proof, it's easier to just
keep compiling them to C